services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ctp
      MYSQL_DATABASE: ctp_la2_poo
    restart: always
    volumes:
      - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "3306:3306"
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ctp
      MONGO_INITDB_ROOT_PASSWORD: ctp
      MONGO_INITDB_DATABASE: ctp
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongodb_network

volumes:
  mongodb_data:

networks:
  mongodb_network:
    driver: bridge
